stages:
    - build
    - test

build:
    stage: build
    script:
        - echo "Building"
        - mkdir build
        - touch build/info.txt
        
test:
    stage: test
    script:
        - echo "Test"
        - test -f "build/"